In [1]:
import tensorflow as tf
x = tf .ones(shape=(2,1)) #= np. 과 동일
print(x)


tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [3]:
y = tf .zeros(shape=(2,1)) #= np. 과 동일
print(y)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [5]:
z = tf.random.normal(shape=(3,1), mean = 0., stddev=1.)
print(z)

tf.Tensor(
[[-0.8934207]
 [-1.0542204]
 [ 1.5780883]], shape=(3, 1), dtype=float32)


In [9]:
a = tf.random.uniform(shape=(3,1), minval = 0., maxval=1.)
print(z)

tf.Tensor(
[[-0.8934207]
 [-1.0542204]
 [ 1.5780883]], shape=(3, 1), dtype=float32)


In [13]:
#Tensor is constant, so we make Variable : tf.Variable

v  = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.23039736],
       [ 1.2606622 ],
       [-0.92142934]], dtype=float32)>


In [ ]:
num_samples_per_class = 1000

negative_samples = np.random.multivariate_normal(
    mean=[0, 3], cov=[[1, 0.5],[0.5, 1]], size=num_samples_per_class)
positive_samples = np.random.multivariate_normal(
    mean=[3, 0], cov=[[1, 0.5],[0.5, 1]], size=num_samples_per_class)

